# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
from collections.abc import Mapping, MutableMapping
from io import IOBase
import inspect
import json
import math
import re
from typing import Any, Callable, IO, Optional, TypeVar, Union, overload
from urllib.parse import SplitResult, unquote, urlsplit
from uuid import UUID

from azure.core import MatchConditions, PipelineClient
from azure.core.credentials import TokenCredential
from azure.core.exceptions import (
    ClientAuthenticationError,
    DecodeError,
    HttpResponseError,
    ResourceExistsError,
    ResourceNotFoundError,
    ResourceNotModifiedError,
    ServiceResponseError,
    StreamClosedError,
    StreamConsumedError,
    map_error,
)
from azure.core.pipeline import PipelineResponse
from azure.core.rest import HttpRequest, HttpResponse
from azure.core.tracing.decorator import distributed_trace
from azure.core.utils import case_insensitive_dict

from .. import models as _models, types as _types
from .._configuration import InferenceClientConfiguration
from .._utils.model_base import SdkJSONEncoder, _deserialize, _failsafe_deserialize
from .._utils.serialization import Serializer
from .._utils.utils import ClientMixinABC

T = TypeVar("T")
ClsType = Optional[Callable[[PipelineResponse[HttpRequest, HttpResponse], T, dict[str, Any]], Any]]

_SERIALIZER = Serializer()
_SERIALIZER.client_side_validation = False

_ONELAKE_FIELDS = frozenset({"onelakeEndpoint", "onelakeWorkspaceId", "onelakeLakehouseId"})
_REQUEST_FIELDS = _ONELAKE_FIELDS | {"text", "documentUrl", "max_words"}
_DEFAULT_MAX_INPUT_BYTES = 1024 * 1024
_AML_SCOPE = "https://ml.azure.com/.default"


def _required_string(request: Mapping[str, object], name: str) -> str:
    value = request.get(name)
    if not isinstance(value, str) or not value:
        raise ValueError(f"'{name}' must be a nonempty string.")
    return value


def _https_url(value: str, name: str) -> SplitResult:
    if any(ord(char) <= 32 or ord(char) == 127 for char in value) or "\\" in value:
        raise ValueError(f"'{name}' must be a URL without whitespace, control characters, or backslashes.")
    parsed = urlsplit(value)
    if (
        parsed.scheme != "https"
        or not parsed.hostname
        or parsed.username is not None
        or parsed.password is not None
        or parsed.port not in (None, 443)
        or "?" in value
        or "#" in value
    ):
        raise ValueError(f"'{name}' must be an HTTPS URL without user information, query parameters, or a fragment.")
    return parsed


def _aml_summarization_url(value: str) -> str:
    endpoint = _https_url(value, "endpoint")
    if not (endpoint.hostname or "").endswith(".inference.ml.azure.com") or endpoint.path not in (
        "",
        "/",
        "/summarize",
        "/summarize/",
    ):
        raise ValueError("Summarization requires a public AML managed endpoint base URL or its full /summarize URL.")
    return f"https://{endpoint.netloc}/summarize"


def _onelake_location(request: Mapping[str, object]) -> tuple[str, str, str]:
    endpoint = _https_url(_required_string(request, "onelakeEndpoint"), "onelakeEndpoint")
    if endpoint.path not in ("", "/") or not re.fullmatch(
        r"(?:[a-z0-9]+-)?onelake\.dfs\.fabric\.microsoft\.com", endpoint.hostname or ""
    ):
        raise ValueError("'onelakeEndpoint' must be a global, regional, or daily OneLake DFS endpoint.")

    identifiers = []
    for name in ("onelakeWorkspaceId", "onelakeLakehouseId"):
        value = _required_string(request, name)
        try:
            identifier = str(UUID(value))
        except ValueError as exc:
            raise ValueError(f"'{name}' must be a dashed GUID.") from exc
        if value.lower() != identifier:
            raise ValueError(f"'{name}' must be a dashed GUID.")
        identifiers.append(identifier)
    workspace_id, lakehouse_id = identifiers

    document = _https_url(_required_string(request, "documentUrl"), "documentUrl")
    if document.hostname != endpoint.hostname:
        raise ValueError("'documentUrl' must use the request's OneLake endpoint, not a Fabric browser link.")
    if re.search(r"%(?![0-9a-fA-F]{2})", document.path):
        raise ValueError("'documentUrl' contains an invalid percent escape.")
    path = unquote(document.path, errors="strict")
    if "%" in path or "\\" in path or any(ord(char) < 32 or ord(char) == 127 for char in path):
        raise ValueError("'documentUrl' contains an unsupported or multiply encoded path.")
    segments = path.split("/")
    if (
        len(segments) < 5
        or segments[0] != ""
        or segments[1].lower() != workspace_id
        or segments[2].lower() != lakehouse_id
        or segments[3] != "Files"
        or any(segment in ("", ".", "..") for segment in segments[1:])
    ):
        raise ValueError("'documentUrl' must identify a file under the request's workspace/lakehouse Files directory.")
    if not segments[-1].lower().endswith((".txt", ".md")):
        raise ValueError("Only UTF-8 .txt and .md documents are supported.")
    return f"https://{endpoint.hostname}", workspace_id, "/".join([lakehouse_id, *segments[3:]])


def _download_onelake_text(
    request: Mapping[str, object],
    credential: TokenCredential,
    max_input_bytes: int,
    connection_timeout: float,
    read_timeout: float,
) -> str:
    endpoint, workspace_id, file_path = _onelake_location(request)
    if not callable(getattr(credential, "get_token", None)) or inspect.iscoroutinefunction(credential.get_token):
        raise TypeError("'onelake_credential' must be a synchronous TokenCredential.")
    for name, value in (("onelake_connection_timeout", connection_timeout), ("onelake_read_timeout", read_timeout)):
        if isinstance(value, bool) or not isinstance(value, (int, float)) or not math.isfinite(value) or value <= 0:
            raise ValueError(f"'{name}' must be a finite positive number of seconds.")

    try:
        from azure.storage.filedatalake import DataLakeFileClient  # pylint: disable=import-outside-toplevel
    except ModuleNotFoundError as exc:
        if exc.name not in ("azure.storage", "azure.storage.filedatalake"):
            raise
        raise ImportError("OneLake downloads require 'azure-data-ai[onelake]'. Install that extra and retry.") from exc

    chunk_size = min(max_input_bytes, 4 * 1024 * 1024)
    with DataLakeFileClient(
        account_url=endpoint,
        file_system_name=workspace_id,
        file_path=file_path,
        credential=credential,
        audience="https://storage.azure.com/",
        connection_timeout=connection_timeout,
        read_timeout=read_timeout,
        retry_total=3,
        retry_to_secondary=False,
        permit_redirects=False,
        max_single_get_size=chunk_size,
        max_chunk_get_size=chunk_size,
    ) as document:
        properties = document.get_file_properties()
        if properties.size > max_input_bytes:
            raise ValueError(f"The document exceeds max_input_bytes ({max_input_bytes}).")
        if properties.size <= 0:
            raise ValueError("The document must not be empty.")
        if properties.content_settings.content_encoding not in (None, "", "identity"):
            raise ValueError("Compressed OneLake documents are not supported.")
        if not properties.etag:
            raise ServiceResponseError("OneLake did not return an ETag for a consistent document download.")

        # Bind the bounded read to the version whose size was checked.
        downloader = document.download_file(
            offset=0,
            length=properties.size,
            etag=properties.etag,
            match_condition=MatchConditions.IfNotModified,
            max_concurrency=1,
            decompress=False,
        )
        data = bytearray()
        for chunk in downloader.chunks():
            if len(data) + len(chunk) > max_input_bytes:
                raise ValueError(f"The document exceeds max_input_bytes ({max_input_bytes}).")
            data.extend(chunk)
        if len(data) != properties.size:
            raise ServiceResponseError("OneLake did not return the complete, size-checked document.")
        return data.decode("utf-8-sig")


def build_inference_semantic_rerank_request(**kwargs: Any) -> HttpRequest:
    _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
    _params = case_insensitive_dict(kwargs.pop("params", {}) or {})

    content_type: Optional[str] = kwargs.pop("content_type", _headers.pop("Content-Type", None))
    api_version: str = kwargs.pop("api_version", _params.pop("api-version", "2026-09-01-preview"))
    accept = _headers.pop("Accept", "application/json")

    # Construct URL
    _url = "/inference/semanticReranking"

    # Construct parameters
    _params["api-version"] = _SERIALIZER.query("api_version", api_version, "str")

    # Construct headers
    if content_type is not None:
        _headers["Content-Type"] = _SERIALIZER.header("content_type", content_type, "str")
    _headers["Accept"] = _SERIALIZER.header("accept", accept, "str")

    return HttpRequest(method="POST", url=_url, params=_params, headers=_headers, **kwargs)


class _InferenceClientOperationsMixin(
    ClientMixinABC[PipelineClient[HttpRequest, HttpResponse], InferenceClientConfiguration]
):

    @overload
    def semantic_rerank(
        self,
        request: _models.SemanticRerankingInferenceContent,
        *,
        content_type: str = "application/json",
        **kwargs: Any
    ) -> _models.SemanticRerankingInferenceResult:
        """Reranks documents by their relevance to a query.

        :param request: The semantic reranking request. Required.
        :type request: ~azure.data.ai.models.SemanticRerankingInferenceContent
        :keyword content_type: Body Parameter content-type. Content type parameter for JSON body.
         Default value is "application/json".
        :paramtype content_type: str
        :return: SemanticRerankingInferenceResult. The SemanticRerankingInferenceResult is compatible
         with MutableMapping
        :rtype: ~azure.data.ai.models.SemanticRerankingInferenceResult
        :raises ~azure.core.exceptions.HttpResponseError:
        """

    @overload
    def semantic_rerank(
        self,
        request: _types.SemanticRerankingInferenceContent,
        *,
        content_type: str = "application/json",
        **kwargs: Any
    ) -> _models.SemanticRerankingInferenceResult:
        """Reranks documents by their relevance to a query.

        :param request: The semantic reranking request. Required.
        :type request: ~azure.data.ai.types.SemanticRerankingInferenceContent
        :keyword content_type: Body Parameter content-type. Content type parameter for JSON body.
         Default value is "application/json".
        :paramtype content_type: str
        :return: SemanticRerankingInferenceResult. The SemanticRerankingInferenceResult is compatible
         with MutableMapping
        :rtype: ~azure.data.ai.models.SemanticRerankingInferenceResult
        :raises ~azure.core.exceptions.HttpResponseError:
        """

    @overload
    def semantic_rerank(
        self, request: Union[bytes, IO[bytes]], *, content_type: str = "application/json", **kwargs: Any
    ) -> _models.SemanticRerankingInferenceResult:
        """Reranks documents by their relevance to a query.

        :param request: The semantic reranking request. Required.
        :type request: bytes or IO[bytes]
        :keyword content_type: Body Parameter content-type. Content type parameter for binary body.
         Default value is "application/json".
        :paramtype content_type: str
        :return: SemanticRerankingInferenceResult. The SemanticRerankingInferenceResult is compatible
         with MutableMapping
        :rtype: ~azure.data.ai.models.SemanticRerankingInferenceResult
        :raises ~azure.core.exceptions.HttpResponseError:
        """

    @distributed_trace
    def semantic_rerank(
        self,
        request: Union[
            _models.SemanticRerankingInferenceContent,
            _types.SemanticRerankingInferenceContent,
            bytes,
            IO[bytes],
        ],
        **kwargs: Any
    ) -> _models.SemanticRerankingInferenceResult:
        """Reranks documents by their relevance to a query.

        :param request: The semantic reranking request. Is either a SemanticRerankingInferenceContent
         type, bytes or an IO[bytes] type. Required.
        :type request: ~azure.data.ai.models.SemanticRerankingInferenceContent or
         ~azure.data.ai.types.SemanticRerankingInferenceContent or bytes or IO[bytes]
        :return: SemanticRerankingInferenceResult. The SemanticRerankingInferenceResult is compatible
         with MutableMapping
        :rtype: ~azure.data.ai.models.SemanticRerankingInferenceResult
        :raises ~azure.core.exceptions.HttpResponseError:
        """
        error_map: MutableMapping = {
            401: ClientAuthenticationError,
            404: ResourceNotFoundError,
            409: ResourceExistsError,
            304: ResourceNotModifiedError,
        }
        error_map.update(kwargs.pop("error_map", {}) or {})

        _headers = case_insensitive_dict(kwargs.pop("headers", {}) or {})
        _params = kwargs.pop("params", {}) or {}

        content_type: Optional[str] = kwargs.pop("content_type", _headers.pop("Content-Type", None))
        cls: ClsType[_models.SemanticRerankingInferenceResult] = kwargs.pop("cls", None)

        content_type = content_type or "application/json"
        _content = None
        if isinstance(request, (IOBase, bytes)):
            _content = request
        else:
            _content = json.dumps(request, cls=SdkJSONEncoder, exclude_readonly=True)  # type: ignore

        _request = build_inference_semantic_rerank_request(
            content_type=content_type,
            api_version=self._config.api_version,
            content=_content,
            headers=_headers,
            params=_params,
        )
        path_format_arguments = {
            "endpoint": self._serialize.url("self._config.endpoint", self._config.endpoint, "str", skip_quote=True),
        }
        _request.url = self._client.format_url(_request.url, **path_format_arguments)

        _decompress = kwargs.pop("decompress", True)
        _stream = kwargs.pop("stream", False)
        pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
            _request, stream=_stream, **kwargs
        )

        response = pipeline_response.http_response

        if response.status_code not in [200]:
            if _stream:
                try:
                    response.read()  # Load the body in memory and close the socket
                except (StreamConsumedError, StreamClosedError):
                    pass
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            error = None
            if response.status_code == 429:
                error = _failsafe_deserialize(_models.TooManyRequestsResult, response)
            else:
                error = _failsafe_deserialize(
                    _models.InferenceErrorResult,
                    response,
                )
            raise HttpResponseError(response=response, model=error)

        response_headers = {}
        response_headers["X-Correlation-ID"] = self._deserialize("str", response.headers.get("X-Correlation-ID"))

        if _stream:
            deserialized = response.iter_bytes() if _decompress else response.iter_raw()
        else:
            deserialized = _deserialize(_models.SemanticRerankingInferenceResult, response.json())

        if cls:
            return cls(pipeline_response, deserialized, response_headers)  # type: ignore

        return deserialized  # type: ignore

    @distributed_trace
    def summarize(
        self,
        request: Mapping[str, object],
        *,
        onelake_credential: Optional[TokenCredential] = None,
        max_input_bytes: int = _DEFAULT_MAX_INPUT_BYTES,
        onelake_connection_timeout: float = 10,
        onelake_read_timeout: float = 60,
        **kwargs: Any,
    ) -> dict[str, Any]:
        """Summarize direct text or a OneLake document using the Qwen3 AML deployment.

        Calls /summarize with text and max_words. This is a deployment-specific
        contract, not a generic AML API. Configure the client with a synchronous
        TokenCredential and credential_scopes=["https://ml.azure.com/.default"].
        Documents are not saved to disk.

        :param request: Exactly one of ``text`` or ``documentUrl``. URL requests also
            require ``onelakeEndpoint``, ``onelakeWorkspaceId``, and ``onelakeLakehouseId``.
            These OneLake settings must come from trusted application configuration.
            Optional ``max_words`` (positive integer, default 100) requests the summary word limit.
            Only the resolved text and max_words are sent to AML.
        :type request: ~collections.abc.Mapping[str, object]
        :keyword onelake_credential: Separate synchronous credential for OneLake.
            Required for document URLs; not serialized or closed by this method.
        :paramtype onelake_credential: ~azure.core.credentials.TokenCredential
        :keyword max_input_bytes: Maximum UTF-8 input size, including any file BOM.
            Defaults to 1 MiB. This is not a model token limit.
        :paramtype max_input_bytes: int
        :keyword onelake_connection_timeout: OneLake connection timeout, in seconds. Default: 10.
        :paramtype onelake_connection_timeout: float
        :keyword onelake_read_timeout: OneLake socket read timeout, in seconds. Default: 60.
            Neither timeout is an overall deadline including retries.
        :paramtype onelake_read_timeout: float
        :return: The AML response JSON object, including the ``summary`` string,
            without normalization.
        :rtype: dict[str, typing.Any]
        :raises ValueError: Invalid inputs, unsupported URLs, or oversized/empty documents.
        :raises UnicodeError: Input is not valid UTF-8.
        :raises ImportError: OneLake support is not installed.
        :raises ~azure.core.exceptions.HttpResponseError: Storage or AML returned an error.
        :raises ~azure.core.exceptions.ServiceRequestError: A network request failed.
        :raises ~azure.core.exceptions.ServiceResponseError: A download or network response failed.
        """
        if not isinstance(request, Mapping):
            raise TypeError("'request' must be a mapping.")
        if set(request) - _REQUEST_FIELDS:
            raise ValueError(
                "Supported request fields are text, documentUrl, max_words, "
                "onelakeEndpoint, onelakeWorkspaceId, and onelakeLakehouseId."
            )
        if ("text" in request) == ("documentUrl" in request):
            raise ValueError("Specify exactly one of 'text' or 'documentUrl'.")
        if isinstance(max_input_bytes, bool) or not isinstance(max_input_bytes, int) or max_input_bytes <= 0:
            raise ValueError("'max_input_bytes' must be a positive integer.")
        if kwargs.pop("stream", False):
            raise ValueError("Streaming summarization responses are not supported by this POC.")

        max_words = request.get("max_words", 100)
        if isinstance(max_words, bool) or not isinstance(max_words, int) or max_words <= 0:
            raise ValueError("'max_words' must be a positive integer.")
        summarization_url = _aml_summarization_url(self._config.endpoint)
        get_token = getattr(self._config.credential, "get_token", None)
        if not callable(get_token) or inspect.iscoroutinefunction(get_token):
            raise TypeError("Direct AML summarization requires a synchronous TokenCredential, not an API key.")
        if list(self._config.credential_scopes) != [_AML_SCOPE]:
            raise ValueError("Create the AML client with credential_scopes=['https://ml.azure.com/.default'].")

        if "text" in request:
            if _ONELAKE_FIELDS.intersection(request):
                raise ValueError("OneLake settings are only accepted with 'documentUrl'.")
            text = _required_string(request, "text")
        else:
            if onelake_credential is None:
                raise ValueError("'onelake_credential' is required for 'documentUrl'.")
            text = _download_onelake_text(
                request, onelake_credential, max_input_bytes, onelake_connection_timeout, onelake_read_timeout
            )
        if len(text) > max_input_bytes or len(text.encode("utf-8")) > max_input_bytes:
            raise ValueError(f"The text exceeds max_input_bytes ({max_input_bytes}).")
        if not text.strip():
            raise ValueError("The text must not be empty or whitespace-only.")

        headers = case_insensitive_dict(kwargs.pop("headers", None) or {})
        headers["Content-Type"] = "application/json"
        headers.setdefault("Accept", "application/json")
        params = dict(kwargs.pop("params", None) or {})
        error_map = {401: ClientAuthenticationError, 403: ClientAuthenticationError, 404: ResourceNotFoundError}
        error_map.update(kwargs.pop("error_map", None) or {})
        kwargs["permit_redirects"] = False
        response = self._client.send_request(
            HttpRequest(
                "POST",
                summarization_url,
                json={"text": text, "max_words": max_words},
                headers=headers,
                params=params,
            ),
            **kwargs,
        )
        if response.status_code != 200:
            map_error(status_code=response.status_code, response=response, error_map=error_map)
            raise HttpResponseError(response=response)
        try:
            result = response.json()
        except ValueError as exc:
            raise DecodeError("The summarization response is not valid JSON.", response=response) from exc
        if not isinstance(result, dict):
            raise DecodeError("The summarization response must be a JSON object.", response=response)
        if not isinstance(result.get("summary"), str):
            raise DecodeError("The AML response must include a 'summary' string.", response=response)
        return result
